### ISSUE TITLE
PR: Django forms fieldset

### ISSUE THREAD

**Issue by hadpro24** [FotieMConstant/made-in-africa#6]
Hello,
Je viens de push ce projet. 
https://github.com/hadpro24/django-forms-fieldset

**Comment by FotieMConstant** [comment]
Hi, @hadpro24, thanks for your interest in adding your repo to this directory. However this repository is only for countries. Please check on your specific country's made-in-[Country name] and add your project to their repository. Only countries feature in this repo.

Thanks.

**Comment by hadpro24** [comment]
Sorry I will add PR soom

**Comment by FotieMConstant** [comment]
Sure, you can submit it anytime!
